title: Serduszko, tralalala
description: co się dzieje
theme: just-the-docs

url: https://mar-zar.github.io/serduszko

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
